config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'home#index'

  devise_for :company_owners
  devise_for :drivers
  devise_for :customers

  resources :companies
  resources :drivers
  resources :company_owners
  resources :customers
  resources :driver_licenses
  resources :goods
  resources :insurance_policies
  resources :orders
  resources :trailers

  post '/actions/take_order', to: 'drivers#take_order'
  post 'actions/finish_order', to: 'drivers#finish_order'
  get '/actions/new_driver_assignment', to: 'orders#new_driver_assignment'
  post 'actions/assign_driver', to: 'orders#assign_driver'

  get '/helpers/truck_select', to: 'trailers#truck_select'
  get '/helpers/driver_select', to: 'trucks#driver_select'
  resources :trucks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Search
  include Handler
  include User
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Handler::RequestError do |exception|
    error_handler(exception)
  end

  private

  def configure_permitted_parameters
    if resource_class == Customer
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name company_phone mobile_phone])
      devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name company_phone mobile_phone])
    elsif resource_class == CompanyOwner
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name phone])
      devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name phone])
    end
  end

  def error_handler(exception)
    flash[:error] = exception.message
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Breadcrumbs
  include DeviseHelper
  include SelectHelper

  def notification_class_for(flash_type)
    {
        notice: 'alert-success',
        error: 'alert-danger',
        alert: 'alert-warning',
        info: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/views/layouts/application/menu/_admin.html.erb
<li class="nav-item active">
  <a class="nav-link" href="<%= companies_path %>">Companies<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= company_owners_path %>">Company owners<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= drivers_path %>">Drivers<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= customers_path %>">Customers<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= driver_licenses_path %>">Driver Licenses<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= goods_path %>">Goods<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= insurance_policies_path %>">Insurance policies<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= orders_path %>">Orders<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= trailers_path %>">Trailers<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= trucks_path %>">Trucks<span class="sr-only">(current)</span></a>
</li>

app/views/layouts/application/menu/_company_owner.html.erb
<li class="nav-item active">
  <a class="nav-link" href="<%= companies_path %>">Companies<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= drivers_path %>">Drivers<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= driver_licenses_path %>">Driver Licenses<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= goods_path %>">Goods<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= insurance_policies_path %>">Insurance policies<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= orders_path %>">Orders<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= trailers_path %>">Trailers<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= trucks_path %>">Trucks<span class="sr-only">(current)</span></a>
</li>

app/views/layouts/application/menu/_customer.html.erb
<li class="nav-item active">
  <a class="nav-link" href="<%= goods_path %>">Goods<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= orders_path %>">Orders<span class="sr-only">(current)</span></a>
</li>

app/views/layouts/application/menu/_driver.html.erb
<li class="nav-item active">
  <a class="nav-link" href="<%= driver_licenses_path %>">Driver Licenses<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= insurance_policies_path %>">Insurance policies<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= orders_path %>">Orders<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= trailers_path %>">Trailers<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="<%= trucks_path %>">Trucks<span class="sr-only">(current)</span></a>
</li>