config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'home#index'

  devise_for :company_owners
  devise_for :drivers
  devise_for :customers

  resources :companies
  resources :drivers
  resources :company_owners
  resources :customers
  resources :driver_licenses
  resources :goods
  resources :insurance_policies
  resources :orders
  resources :trailers

  post '/actions/take_order', to: 'drivers#take_order'
  post 'actions/finish_order', to: 'drivers#finish_order'
  get '/actions/new_driver_assignment', to: 'orders#new_driver_assignment'
  post 'actions/assign_driver', to: 'orders#assign_driver'

  get '/helpers/truck_select', to: 'trailers#truck_select'
  get '/helpers/driver_select', to: 'trucks#driver_select'
  resources :trucks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trailer.rb
class Trailer < ApplicationRecord
  belongs_to :truck, optional: true
  belongs_to :company
end

app/controllers/trailers_controller.rb
# frozen_string_literal: true

class TrailersController < ApplicationController
  def index
    handle(run(Trailer::Index, current_user: current_user)) do |result|
      @trailers = search_for(result[:model]).page(params[:page])
    end
  end

  def new
    handle(run(Trailer::Create::Present, current_user: current_user))
  end

  def create
    handle(run(Trailer::Create, current_user: current_user)) do |result|
      return redirect_to trailer_path(result[:model]), notice: "Trailer #{result[:model].reg_number} successfully created"
    end

    render :new
  end

  def show
    handle(run(Trailer::Show, current_user: current_user))
  end

  def edit
    handle(run(Trailer::Update::Present, current_user: current_user))
  end

  def update
    handle(run(Trailer::Update, current_user: current_user)) do |result|
      return redirect_to trailer_path(result[:model]), notice: "Trailer #{result[:model].reg_number} successfully updated"
    end

    render :edit
  end

  def destroy
    handle(run(Trailer::Delete, current_user: current_user)) do |result|
      return redirect_to trailers_path, notice: "Trailer #{result[:model].reg_number} removed successfully"
    end
  end

  def truck_select
    if params[:selected_company_id].present?
      trucks = Company.find(params[:selected_company_id]).trucks
    end
    respond_to do |format|
      format.json { render json: trucks }
      format.html
    end
  end
end

app/views/trailers/_form.html.erb
<%= render 'layouts/application/form_errors', form: @form %>
<%= form_for @form do |f| %>
  <div class="col-md-6 offset-md-3">
    <div class=" form-group row">
      <%= f.label :reg_number, 'Reg number', class: "col-form-label" %>
      <div class="col">
        <%= f.text_field :reg_number, class: 'form-control', placeholder: 'AA-0000-0' %>
      </div>
      <%= f.label :color, 'Color', class: "col-form-label" %>
      <div class="col">
        <%= f.text_field :color, class: 'form-control', placeholder: 'Green' %>
      </div>
    </div>
    <div class="form-group row">
        <%= f.label :year_of_issue, 'Year of issue', class: "col-form-label" %>
      <div class="col">
        <%= f.select :year_of_issue, (Time.now.year).downto(Time.now.year - 30).to_a, {}, class: 'form-control', prompt: 'Select year' %>
      </div>
      <%= f.label :trailer_type, 'Type', class: "col-form-label" %>
      <div class="col">
        <%= f.text_field :trailer_type, class: 'form-control', placeholder: 'Long' %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :weight, 'Weight', class: "col-form-label" %>
      <div class="col">
        <%= f.text_field :weight, class: 'form-control', placeholder: '1000kg' %>
      </div>
      <%= f.label :length, 'Length', class: "col-form-label" %>
      <div class="col">
        <%= f.text_field :length, class: 'form-control', placeholder: '10m' %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :height, 'Height', class: "col-form-label" %>
      <div class="col">
        <%= f.text_field :height, class: 'form-control', placeholder: '5m' %>
      </div>
      <%= f.label :volume, 'Volume', class: "col-form-label" %>
      <div class="col">
        <%= f.text_field :volume, class: 'form-control', placeholder: '50m3' %>
      </div>
    </div>
    <% unless current_driver %>
      <div class="form-group row">
        <%= f.label :company_id, 'Company', class: "col-form-label" %>
        <div class="col">
          <%= f.select :company_id, company_select, {prompt: 'Select company'}, id: 'trailer_company_id', class: 'form-control '%>
        </div>
        <%= f.label :truck_id, 'Truck', class: "col-form-label" %>
        <div class="col">
            <%= f.select :truck_id, '', {prompt: 'Select truck'}, class: 'form-control', id: 'trailer_truck_id'%>
        </div>
      </div>
    <% end %>
    <div class="form-group offset-md-5">
      <%= f.submit 'Submit', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/trailers/_search.html.erb
<div class="col-md-12 offset-md-1" style="margin-bottom: 15px" >
<%= search_form_for @search, url: trailers_path, method: :get, class: "form-inline my-2 my-lg-0" do |f| %>
  <%= f.search_field :reg_number_cont, class: 'form-control mr-sm-2', placeholder: 'Reg number contains' %>
    <%= f.search_field :trailer_type_cont, class: 'form-control mr-sm-2', placeholder: 'Type contains' %>
    <%= f.search_field :length_eq, class: 'form-control mr-sm-2', placeholder: 'Length equals' %>
    <%= f.search_field :volume_eq, class: 'form-control mr-sm-2', placeholder: 'Volume equals' %>
  <div class="form-group">
    <%= f.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0', style: 'margin-right: 10px' %>
    <%= link_to 'Reset', {}, class: 'btn btn-outline-danger my-2 my-sm-0' %>
  </div>
<% end %>
</div>

app/views/trailers/edit.html.erb
<div class="breadcrumbs">
  <nav aria-label="breadcrumb">
    <%= breadcrumbs do %>
      <%= breadcrumb 'Trailers', trailers_path %>
      <%= breadcrumb @form.model.id, trailer_path(@form.model) %>
      <%= breadcrumb 'Edit' %>
    <% end %>
  </nav>
</div>

<%= render 'form' %>

app/views/trailers/index.html.erb
<div class="breadcrumbs">
  <nav aria-label="breadcrumb" >
    <%= breadcrumbs do %>
      <%= breadcrumb 'Trailers' %>
    <% end %>
    <% unless current_driver %>
      <%= link_to 'New trailer', new_trailer_path, class: 'btn btn-sm btn-primary action-button' %>
    <% end %>
  </nav>
</div>

<%= render 'search' %>

<table class="table">
  <thead>
  <tr>
    <th scope="col"><%= sort_link @search, :reg_number, 'Reg number' %></th>
    <th scope="col"><%= sort_link @search, :color, 'Color' %></th>
    <th scope="col"><%= sort_link @search, :type, 'Type' %></th>
    <th scope="col"><%= sort_link @search, :year_of_issue, 'Year of issue' %></th>
    <th scope="col"><%= sort_link @search, :truck_id, 'Truck' %></th>
    <th scope="col"><%= sort_link @search, :company_id, 'Company' %></th>
    <% unless current_driver %>
      <th scope="col" colspan="2">Actions</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% @trailers.each do |trailer| %>
  <tr>
    <td><%= link_to trailer.reg_number, trailer_path(trailer) %></td>
    <td><%= trailer.color %></td>
    <td><%= trailer.trailer_type %></td>
    <td><%= trailer.year_of_issue %></td>
    <% if trailer.truck %>
      <td><%= link_to trailer.truck.reg_number, truck_path(trailer.truck) %></td>
    <% else %>
      <td>N/A</td>
    <% end %>
    <% if trailer.company %>
      <td><%= link_to trailer.company.name, company_path(trailer.company) %></td>
    <% else %>
      <td>N/A</td>
    <% end %>
    <% unless current_driver %>
      <td><%= link_to 'Edit', edit_trailer_path(trailer), class: 'btn btn-success' %></td>
      <td><%= link_to 'Delete', trailer_path(trailer), method: :delete,
                    class: 'btn btn-danger', data: { confirm: 'Are you sure?' }%></td>
    <% end %>
  </tr>
  <% end %>
  </tbody>
  <div class="container pagination justify-content-center">
    <%= paginate @trailers %>
  </div>
</table>

app/views/trailers/new.html.erb
<div class="breadcrumbs">
  <nav aria-label="breadcrumb" >
    <%= breadcrumbs do %>
      <%= breadcrumb 'Insurance policies', insurance_policies_path %>
      <%= breadcrumb 'New' %>
    <% end %>
  </nav>
</div>

<%= render 'form' %>

app/views/trailers/show.html.erb
<div class="breadcrumbs">
  <nav aria-label="breadcrumb" >
    <%= breadcrumbs do %>
      <%= breadcrumb 'Trailers', trailers_path %>
      <%= breadcrumb "#{@model.id}" %>
    <% end %>
  </nav>
</div>

<ul class="list-group">
  <li class="list-group-item"><strong>Reg number: </strong><%= @model.reg_number %></li>
  <li class="list-group-item"><strong>Color: </strong><%= @model.color%></li>
  <li class="list-group-item"><strong>Type: </strong><%= @model.trailer_type %></li>
  <li class="list-group-item"><strong>Weight: </strong><%= @model.weight %></li>
  <li class="list-group-item"><strong>Length: </strong><%= @model.length %></li>
  <li class="list-group-item"><strong>Height: </strong><%= @model.height %></li>
  <li class="list-group-item"><strong>Volume: </strong><%= @model.volume %></li>
  <% if @model.truck %>
    <li class="list-group-item"><strong>Truck: </strong><%= link_to @model.truck.reg_number, truck_path(@model.truck) %></li>
  <% else %>
    <li class="list-group-item"><strong>Truck: </strong> N/A </li>
  <% end %>
  <% if @model.company %>
    <li class="list-group-item">
      <strong>Company: </strong><%= link_to @model.company.name, company_path(@model.company) %></li>
  <% else %>
    <li class="list-group-item">
      <strong>Company: </strong>N/A</li>
  <% end %>
  <li class="list-group-item"><strong>Actions: </strong>
    <%= link_to 'Edit', edit_trailer_path(@model), class: 'btn btn-success btn-sm' %>
    <%= link_to 'Delete', trailer_path(@model),
                class: 'btn btn-danger btn-sm', method: :delete,
                data: {confirm: 'Are you sure?'} %>
  </li>
</ul>