config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'home#index'

  devise_for :company_owners
  devise_for :drivers
  devise_for :customers

  resources :companies
  resources :drivers
  resources :company_owners
  resources :customers
  resources :driver_licenses
  resources :goods
  resources :insurance_policies
  resources :orders
  resources :trailers

  post '/actions/take_order', to: 'drivers#take_order'
  post 'actions/finish_order', to: 'drivers#finish_order'
  get '/actions/new_driver_assignment', to: 'orders#new_driver_assignment'
  post 'actions/assign_driver', to: 'orders#assign_driver'

  get '/helpers/truck_select', to: 'trailers#truck_select'
  get '/helpers/driver_select', to: 'trucks#driver_select'
  resources :trucks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/good.rb
class Good < ApplicationRecord
  has_many :goods_orders, dependent: :delete_all
  has_many :orders, through: :goods_orders, dependent: :destroy
  belongs_to :customer, dependent: :destroy

  def info
    "#{name}(#{goods_type})"
  end
end

app/controllers/goods_controller.rb
# frozen_string_literal: true

class GoodsController < ApplicationController
  def index
    handle(run(Good::Index, current_user: current_user)) do |result|
      @goods = search_for(result[:model]).page(params[:page])
    end
  end

  def new
    handle(run(Good::Create::Present, current_user: current_user))
  end

  def create
    handle(run(Good::Create, current_user: current_user)) do |result|
      return redirect_to good_path(result[:model]), notice: "Good #{result[:model].name} successfully created"
    end

    render :new
  end

  def show
    handle(run(Good::Show, current_user: current_user))
  end

  def edit
    handle(run(Good::Update::Present, current_user: current_user))
  end

  def update
    handle(run(Good::Update, current_user: current_user)) do |result|
      return redirect_to good_path(result[:model]), notice: "Good #{result[:model].name} successfully updated"
    end

    render :edit
  end

  def destroy
    handle(run(Good::Delete, current_user: current_user)) do |result|
      return redirect_to goods_path, notice: "Good #{result[:model].name} removed successfully"
    end
  end
end

app/views/goods/_form.html.erb
<%= render 'layouts/application/form_errors', form: @form %>
<%= form_for @form do |f| %>
  <div class="col-md-10 offset-md-4">
    <div class="form-group row" >
      <%= f.label :name, 'Name', class: "col-sm-1 col-form-label" %>
      <div class="col-sm-10'">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Google' %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :weight, 'Weight', class: "col-sm-1 col-form-label" %>
      <div class="col-sm-10'">
        <%= f.text_field :weight, class: 'form-control', placeholder: 'Weight in kg(primary)' %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :volume, 'Volume', class: "col-sm-1 col-form-label" %>
      <div >
        <%= f.text_field :volume, class: 'form-control', placeholder: 'Volume in m3' %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :goods_type, 'Goods type', class: "col-sm-1 col-form-label" %>
      <div>
        <%= f.text_field :goods_type, class: 'form-control', placeholder: 'Clothes' %>
      </div>
    </div>
    <% unless current_customer %>
      <div class="form-group row">
        <%= f.label :customer_id, 'Customer', class: "col-sm-1 col-form-label" %>
        <div>
          <%= f.select :customer_id, customer_select, {}, class: 'form-control col-sm-6', prompt: 'Select customer' %>
        </div>
      </div>
    <% else %>
      <%= f.hidden_field :customer_id, value: current_customer.id %>
    <% end %>
    <div class="form-group offset-md-1">
      <%= f.submit 'Submit', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/goods/_search.html.erb
<div class="col-md-8 offset-md-3" style="margin-bottom: 15px" >
<%= search_form_for @search, url: goods_path, method: :get, class: "form-inline my-2 my-lg-0" do |f| %>
  <%= f.search_field :name_cont, class: 'form-control mr-sm-2', placeholder: 'Name contains' %>
    <%= f.search_field :goods_type_cont, class: 'form-control mr-sm-2', placeholder: 'Goods type contains' %>
  <div class="form-group">
    <%= f.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0', style: 'margin-right: 10px' %>
    <%= link_to 'Reset', {}, class: 'btn btn-outline-danger my-2 my-sm-0' %>
  </div>
<% end %>
</div>

app/views/goods/edit.html.erb
<div class="breadcrumbs">
  <nav aria-label="breadcrumb">
    <%= breadcrumbs do %>
      <%= breadcrumb 'Goods', goods_path %>
      <%= breadcrumb @form.model.id, goods_path(@form.model) %>
      <%= breadcrumb 'Edit' %>
    <% end %>
  </nav>
</div>

<%= render 'form' %>

app/views/goods/index.html.erb
<div class="breadcrumbs">
  <nav aria-label="breadcrumb" >
    <%= breadcrumbs do %>
      <%= breadcrumb 'Goods' %>
    <% end %>
    <% unless current_company_owner %>
      <%= link_to 'New goods', new_good_path, class: 'btn btn-sm btn-primary action-button' %>
    <% end %>
  </nav>
</div>

<%= render 'search' %>

<table class="table">
  <thead>
  <tr>
    <th scope="col"><%= sort_link @search, :name, 'Name' %></th>
    <th scope="col"><%= sort_link @search, :weight, 'Weight' %></th>
    <th scope="col"><%= sort_link @search, :volume, 'Volume' %></th>
    <th scope="col"><%= sort_link @search, :goods_type, 'Type' %></th>
    <% if current_admin %>
      <th scope="col"><%= sort_link @search, :customer_id, 'Customer' %></th>
    <% end %>
    <% unless current_company_owner %>
      <th scope="col" colspan="2">Actions</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% @goods.each do |goods| %>
  <tr>
    <td><%= link_to goods.name, good_path(goods) %></td>
    <td><%= goods.weight %></td>
    <td><%= goods.volume %></td>
    <td><%= goods.goods_type %></td>
    <% if current_admin %>
      <td><%= link_to goods.customer.email, customer_path(goods.customer) %></td>
    <% end %>
    <% unless current_company_owner %>
      <td><%= link_to 'Edit', edit_good_path(goods), class: 'btn btn-success' %></td>
      <td><%= link_to 'Delete', good_path(goods), method: :delete,
                      class: 'btn btn-danger', data: { confirm: 'Are you sure?' }%></td>
    <% end %>
  </tr>
  <% end %>
  </tbody>
  <div class="container pagination justify-content-center">
    <%= paginate @goods %>
  </div>
</table>

app/views/goods/new.html.erb
<div class="breadcrumbs">
  <nav aria-label="breadcrumb" >
    <%= breadcrumbs do %>
      <%= breadcrumb 'Goods', goods_path %>
      <%= breadcrumb 'New' %>
    <% end %>
  </nav>
</div>

<%= render 'form' %>

app/views/goods/show.html.erb
<div class="breadcrumbs">
  <nav aria-label="breadcrumb" >
    <%= breadcrumbs do %>
      <%= breadcrumb 'Goods', goods_path %>
      <%= breadcrumb "#{@model.id}" %>
    <% end %>
  </nav>
</div>

<ul class="list-group">
  <li class="list-group-item"><strong>Name: </strong><%= @model.name %></li>
  <li class="list-group-item"><strong>Weight: </strong><%= @model.weight%></li>
  <li class="list-group-item"><strong>Volume: </strong><%= @model.volume %></li>
  <li class="list-group-item"><strong>Goods type: </strong><%= @model.goods_type %></li>
  <% if current_admin %>
    <li class="list-group-item"><strong>Customer: </strong><%= link_to @model.customer.info, customer_path(@model.customer) %></li>
  <% end %>
  <% unless current_company_owner %>
    <li class="list-group-item"><strong>Actions: </strong>
      <%= link_to 'Edit', edit_good_path(@model), class: 'btn btn-success btn-sm' %>
      <%= link_to 'Delete', good_path(@model),
                  class: 'btn btn-danger btn-sm', method: :delete,
                  data: {confirm: 'Are you sure?'} %>
  </li>
  <% end %>
</ul>